FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

WORKDIR /subgen

RUN apt-get update && apt-get -y install python3 python3-pip ffmpeg

ENV PYTHONUNBUFFERED 1

ADD https://raw.githubusercontent.com/McCloudS/subgen/main/bootstrap.sh /bootstrap.sh
RUN chmod +x /bootstrap.sh

CMD [ "/bootstrap.sh" ]

EXPOSE 8090
